export const regionMap = {
  global: 'global',
  southeastAsiaPacific1: 'ap-bangkok',
  southeastAsiaPacific2: 'ap-jakarta',
  northChina: 'ap-beijing',
  southwestChina1: 'ap-chengdu',
  southwestChina2: 'ap-chongqing',
  southChina1:	'ap-guangzhou',
  southChina2: 'ap-shenzhen-fsi',
  hongKong: 'ap-hongkong',
  southAsiaPacific: 'ap-mumbai',
  eastChina: 'ap-nanjing',
  northeastAsiaPacific1:	'ap-seoul',
  northeastAsiaPacific2: 'ap-tokyo',
  eastChina1: 'ap-shanghai',
  eastChina2: 'ap-shanghai-fsi',
  southeastAsiaPacific: 'ap-singapore',
  europe1: 'eu-frankfurt',
  europe2: 'eu-moscow',
  easternUS: 'na-ashburn',
  westernUS: 'na-siliconvalley',
  northAmerica: 'na-toronto',
  southAmerica: 'sa-saopaulo',
}

const {
  global,
  southeastAsiaPacific1,
  southeastAsiaPacific2,
  northChina,
  southwestChina1,
  southwestChina2,
  southChina1,
  southChina2,
  hongKong,
  southAsiaPacific,
  eastChina,
  northeastAsiaPacific1,
  northeastAsiaPacific2,
  eastChina1,
  eastChina2,
  southeastAsiaPacific,
  europe1,
  europe2,
  easternUS,
  westernUS,
  northAmerica,
  southAmerica,
} = regionMap

export default [
  global,
  southeastAsiaPacific1,
  southeastAsiaPacific2,
  northChina,
  southwestChina1,
  southwestChina2,
  southChina1,
  southChina2,
  hongKong,
  southAsiaPacific,
  eastChina,
  northeastAsiaPacific1,
  northeastAsiaPacific2,
  eastChina1,
  eastChina2,
  southeastAsiaPacific,
  europe1,
  europe2,
  easternUS,
  westernUS,
  northAmerica,
  southAmerica,   
]
