export default {
  camPolicy: 'camPolicy',
  ccn: 'ccn',
  ccnAttachment: 'ccnAttachment',
  customerGateway: 'customerGateway',
  networkAcl: 'networkAcl',
  routeTable: 'routeTable',
  securityGroup: 'securityGroup',
  securityGroupRule: 'securityGroupRule',
  subnet: 'subnet',
  vpc: 'vpc',
  vpnConnection: 'vpnConnection',
  vpnGateway: 'vpnGateway',
  vpnGatewayRoute: 'vpnGatewayRoute',
}
